#184760061 - Add/View Wishlist
atlp-rwanda/trojans-ec-fe pull request #21
Opened 2023-04-22 11:28 UTC by Marthatwesi

2023-04-24 14:09 UTC, Ntarecedrick approved these changes

2023-04-24 14:20 UTC, teerenzo approved these changes

2023-04-26 09:49 UTC, Eli250 requested changes

2023-04-26 09:49 UTC, Eli250 commented on src/components/hooks/useSingleMainView.js
> +        if (error.payload === 401) {
Get rid of this nested if statement.

2023-04-26 09:49 UTC, Eli250 commented on src/components/viewProducts/SingleMainView.js
> +    if (wishError.payload === 401) {
Remove nexted if blocks

2023-04-26 09:49 UTC, Eli250 commented on src/redux/features/actions/wishlist.js
> +    if(error.response){
Get rid of this if block

2023-04-26 09:49 UTC, Eli250 commented on src/redux/features/actions/wishlist.js
> +    if (error.response) {
This if condition is redundant

2023-04-26 09:49 UTC, Eli250 commented on src/redux/features/actions/wishlist.js
> +       return error.response.data;
Get rid of this condition

2023-04-26 09:49 UTC, Eli250 commented on src/redux/features/slices/wishlist.js
> +            console.log("fulfilled")
?

2023-04-26 09:49 UTC, Eli250 commented on src/redux/features/slices/wishlist.js
> +            console.log("fulfilled")
?

2023-04-27 15:21 UTC, Eli250 approved these changes

2023-04-27 15:25 UTC, merged