#184760050 Ft admin disable account
atlp-rwanda/trojans-ec-fe pull request #27
Opened 2023-04-28 13:04 UTC by suave990

What does PR do
This task is for Admin  disabling/Enabling Accounts
Description of the task 
this PR is to add a feature so that Admin dashboard should list all users with the option of disabling accounts
Due to varying reasons e.g fraud, abuse, malicious use or violation of terms of service, admin should be able to disable any user account.

How should it be tested manually
to test this feature manually you can login as an Admin and navigate to disable account then from there one may enable or disable the accounts
route:`/dashboard/users`

Any background context you want to provide ?
N/A

What are the relevant pivotal tracker stories
https://www.pivotaltracker.com/n/projects/2628461

Screenshots(if appropriate)
<img width="1433" alt="Screenshot 2023-05-04 at 16 41 32" src="https://user-images.githubusercontent.com/117984063/236241550-90b7bcf3-99bd-4b63-bd72-ce2d04b8b3ad.png">

2023-05-02 14:17 UTC, Eli250 requested changes
Remove unnecessary comments.

2023-05-04 11:44 UTC, UwaweTera approved these changes

2023-05-04 12:11 UTC, NG-Solennel approved these changes

2023-05-04 14:58 UTC, Eli250 approved these changes

2023-05-04 14:58 UTC, Ntarecedrick approved these changes

2023-05-04 15:11 UTC, merged