#184760032 Set codeclimate
atlp-rwanda/trojans-ec-fe pull request #8
Opened 2023-03-28 18:00 UTC by jimmymut

### what does the PR do?
This PR is to setup codeclimate

### Description of the task
The task is to set codeclimate to our project to enforce better code maintenance

### How can it be manually tested

Only check the maintainability badge on the readme

### Any background context you want to provide

None

### what is your pivotal tracker link ?
https://www.pivotaltracker.com/story/show/184760032

2023-03-28 18:32 UTC, Ntarecedrick approved these changes

2023-03-28 19:28 UTC, UwaweTera approved these changes

2023-03-29 06:13 UTC, NG-Solennel approved these changes

2023-03-29 08:16 UTC, denislohan approved these changes

2023-03-29 08:17 UTC, denislohan requested changes
Your commit is named wrong!

2023-03-29 15:18 UTC, Eli250 approved these changes

2023-03-29 17:12 UTC, denislohan approved these changes

2023-03-29 17:12 UTC, merged